spring.application.name=taskmanager

spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanagerdatabese
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 

api.security.token.secret=${JWT_SECRET:my-secret-key}